### ISSUE TITLE
Module breaks on missing 'vendor' in 'network_controller'

### ISSUE THREAD

**Issue by pizzapim** [numtide/nixos-facter-modules#54]
**Describe the bug**

Sometimes the `vendor` field is absent from the items in `report.hardware.network_controller`. The code makes the assumption it is always populated.

```
$ nix build '.#nixosConfigurations.warwick.config.system.build.toplevel'
warning: Git tree '/home/pim/git/nixos-servers' is dirty
error:
       … while calling the 'head' builtin

         at /nix/store/rfq6hpk4a4ki1q1856qpb846admnwq5d-source/lib/attrsets.nix:1575:11:

         1574|         || pred here (elemAt values 1) (head values) then
         1575|           head values
             |           ^
         1576|         else

       … while evaluating the attribute 'value'

         at /nix/store/rfq6hpk4a4ki1q1856qpb846admnwq5d-source/lib/modules.nix:809:9:

          808|     in warnDeprecation opt //
          809|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          810|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: function 'anonymous lambda' called without required argument 'vendor'

       at /nix/store/dzg9himrl8kvwik6r00cgbjcx4ya7x81-source/modules/nixos/networking/intel.nix:11:9:

           10|       default = lib.any (
           11|         { vendor, device, ... }:
             |         ^
           12|         # vendor (0x8086) Intel Corp.
```

This is a Raspberry Pi 4 and it detects a WiFi and Ethernet network controller. However, only the WiFi controller has the vendor field populated.
```
# cat facter.json | jq '.hardware.network_controller[].vendor'
null # One does not have a vendor field
{
  "name": "Broadcom Corp.",
  "value": 720
}
```

**System information**

```
OS: NixOS 24.05.20240729.12bf098 (Uakari) aarch64
Host: Raspberry Pi 4 Model B Rev 1.5
Kernel: Linux 6.1.63
CPU: Cortex-A72 (4) @ 1,80 GHz
```

Full JSON of the network controller

<details><summary>Details</summary>
<p>

  {
    "index": 9,
    "attached_to": 0,
    "base_class": {
      "name": "Network controller",
      "value": 2
    },
    "sub_class": {
      "name": "WLAN controller",
      "value": 130
    },
    "device": {
      "name": "ARM Ethernet controller",
      "value": 0
    },
    "model": "ARM Ethernet controller",
    "sysfs_id": "/devices/platform/soc/fe300000.mmcnr/mmc_host/mmc1/mmc1:0001/mmc1:0001:1",
    "sysfs_bus_id": "mmc1:0001:1",
    "unix_device_name": "wlan0",
    "unix_device_names": [
      "wlan0"
    ],
    "resources": [
      {
        "type": "hwaddr",
        "address": 100
      },
      {
        "type": "phwaddr",
        "address": 100
      },
      {
        "type": "wlan",
        "channels": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "34",
          "36",
          "38",
          "40",
          "42",
          "44",
          "46",
          "48",
          "52",
          "56",
          "60",
          "64",
          "100",
          "104",
          "108",
          "112",
          "116",
          "120"
        ],
        "frequencies": [
          "2.412",
          "2.417",
          "2.422",
          "2.427",
          "2.432",
          "2.437",
          "2.442",
          "2.447",
          "2.452",
          "2.457",
          "2.462",
          "2.467",
          "2.472",
          "2.484",
          "5.17",
          "5.18",
          "5.19",
          "5.2",
          "5.21",
          "5.22",
          "5.23",
          "5.24",
          "5.26",
          "5.28",
          "5.3",
          "5.32",
          "5.5",
          "5.52",
          "5.54",
          "5.56",
          "5.58",
          "5.6"
        ],
        "auth_modes": [
          "open",
          "sharedkey",
          "wpa-psk",
          "wpa-eap"
        ],
        "enc_modes": [
          "WEP40",
          "WEP104",
          "TKIP",
          "CCMP"
        ]
      }
    ],
    "driver": "brcmfmac",
    "driver_module": "brcmfmac",
    "drivers": [
      "brcmfmac"
    ],
    "driver_modules": [
      "brcmfmac",
      "brcmfmac",
      "brcmfmac"
    ],
    "module_alias": "of:NmmcnrT(null)Cbrcm,bcm2835-mmcCbrcm,bcm2835-sdhci"
  },

</p>
</details> 

Might also be a bug in the facter itself?

**Comment by brianmcgee** [comment]
This is an easy enough fix. I'll have a look later today.
