### ISSUE TITLE
Make detectable items always available

### ISSUE THREAD

**Issue by arunoruto** [numtide/nixos-facter-modules#60]
**Is your feature request related to a problem? Please describe.**

I cam across #58 and wanted to try it out on my Framework and it works amazingly. I used then `config.facter.detected.fingerprint.enable` as the default value for my custom module for fingerprints. But `config.facter.detected.fingerprint.enable` is only available if, and only if, a fingerprint sensor is present. So before using the option, I would have to check if `config.facter.detected` has the `fingerprint` attribute, but then I can just use the output of that check, since it will only be present if facter found a fingerprint sensor.

**Describe the solution you'd like**

Have `config.facter.detected.fingerprint.enable`, and others, be present all the time.

**Describe alternatives you've considered**

Currently I am setting the value with `facter.detected.fingerprint.enable = lib.mkOverride 2000 false`.

**Additional context**

With keeping potential detectable items in the list, one can even explore what can be detected for now. If they have the hardware but it is not enabled, they can easier notice it and report potential issues.

**Comment by Mic92** [comment]
Are you sure, you are using the latest version? This config is always available to me, even if no fingerprint is available:

```
nix-repl> :p nixosConfigurations.turingmachine.config.facter.detected.fingerprint.enable 
true
nix-repl> :p nixosConfigurations.eve.config.facter.detected.fingerprint.enable           
false
```

**Comment by arunoruto** [comment]
> Are you sure, you are using the latest version? This config is always available to me, even if no fingerprint is available:
> 
> ```
> nix-repl> :p nixosConfigurations.turingmachine.config.facter.detected.fingerprint.enable 
> true
> nix-repl> :p nixosConfigurations.eve.config.facter.detected.fingerprint.enable           
> false
> ```

You are totally right. I am not sure why... I even checked with `nix flake update` to have the newest version of the flake on all systems. But it seems to be now available and I can drop my `mkOverride` from the config without a problem.

Sorry for the false alarm!
